GC2WH2/Controllers/MirrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GC2;
using GC2DB.Data;
using GC2DB.Managers;
using GC2WH2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GC2WH2.Controllers
{
    public class MirrorController : Controller
    {
        public IActionResult Index(string id)
        {
            var model = new MirrorModel();
            if (!String.IsNullOrWhiteSpace(id))
            {
                Player player = GameManager.GetPlayerByMirrorId(id);
                if (player != null)
                {
                    model.Player = player;
                    model.Game = player.Game;
                    model.User = new GcUser()
                    {
                        TelegramUserId = player.ChatId
                    };

                }
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Game(GameInfo gi)
        {
            if (gi.Guid == null || gi.Key == null)
                return Index(null);
            if (!String.IsNullOrWhiteSpace(gi.Secret))
            {
                if (gi.Game == null)
                {
                    var games = GameManager.GetActiveGameByGuid(gi.Guid);
                    if (games != null && games.Count == 1)
                    {
                        gi.Game = games[0];
                    }
                    else
                    {
                        return View("Index", null);
                    }
                }
                ProcessingManager.CheckSecretForMirror(gi.Game, gi.Key, gi.Secret);

                if (gi.Tasks == null && gi.Game.LastTaskId.HasValue)
                {
                    var lastTask = GameManager.GetTaskById(gi.Game.LastTaskId.Value);
                    if (lastTask != null)
                    {
                        gi.Tasks = new List<GameTask>()
                        {
                            lastTask
                        };
                    }
                }
                return View("Game", gi);
            }
            else
            {
                return View("NoAuth", gi);
            }
            return Index(null);
        }

        public IActionResult Game(string id)
        {
            if (id == null)
            {
                Index(null);
            }
            else if (id.Length == 16)
            {
                GameInfo gi = ParseGameInfo(id);
                return View("NoAuth", gi);
            }

            return Index(null);
        }

        public GameInfo ParseGameInfo(string input)
        {
            GameInfo result = new GameInfo();

            if (input.Length != 16)
            {
                return null;
            }

            var parts = input.Split(new char[] { '-' }, StringSplitOptions.RemoveEmptyEntries);
            if (parts.Length < 2 || parts.Length > 3)
            {
                return null;
            }
            var games = GameManager.GetActiveGameByGuid(parts[0]);
            if (games == null || games.Count != 1)
            {
                return null;
            }
            else
            {
                result.Game = games[0];
            }
            if (!long.TryParse(parts[1], out var key))
            {
                return null;
            }
            if (parts.Length == 2)
            {
                result.Guid = parts[0];
                result.Key = key;
            }

            return result;
        }
    }
}

GC2WH2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GC2WH</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GC2WH</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Status">Status</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mirror" asp-action="Index">Mirror</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="@((@ViewData["FullScreen"] == null) ? "container" : "" )">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Icy
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

GC2WH2/Views/Shared/_ValidationScriptsPartial - Copy.cshtml
<environment include="Development">
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"
            asp-fallback-src="~/lib/jquery-validation/dist/jquery.validate.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.validator"
            crossorigin="anonymous"
            integrity="sha256-F6h55Qw6sweK+t7SiOJX+2bpSAa3b/fnlrVCJvmEj1A=">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"
            asp-fallback-src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive"
            crossorigin="anonymous"
            integrity="sha256-9GycpJnliUjJDVDqP0UEu/bsm9U+3dnQUH8+3W10vkY=">
    </script>
</environment>